### ISSUE TITLE
Verwijder onnodige commentaar regels

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#1]
Voor zowel **"LoginController.java"** als de **"OverviewController.java"**

Door het hele bestand staat bijna bij elke regel commentaar. Soms is dit Javadoc maar je ziet vooral veel inline commentaar.

Probeer onnodig commentaar te verwijderen of te herschrijven

**Comment by joeryhuiden** [comment]
alle commentaar verwijderd, heeft geen meerwaarde

**Comment by joeryhuiden** [comment]
wel een paar commentaar regels in OverviewController toegevoegd.
