### ISSUE TITLE
Aanmaken van constanten

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#12]
Op de MailService.java

Van de volgende strings (en integers) kunnen ook constanten van worden gemaakt

Zo kan een andere developer deze makkelijk onder elkaar aanpassen 

``` java
        prop.put("mail.smtp.from", "info.familyweb@gmail.com");
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", 465);
        prop.put("mail.smtp.auth", true);
        prop.put("mail.smtp.ssl.enable", true);
```

LET OP dit gebeurt niet alleen bij het voorbeeld. Bijna elke string in deze klasse kan een constante worden!

**Comment by joeryhuiden** [comment]
De constante zijn aangemaakt.
