### ISSUE TITLE
Methode naam veranderen en nieuwe methodes maken

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#14]
In de MailService.java staat de methode:

``` java
public boolean sendMail() {
```

Deze methode doet alleen naast het verzenden van de mail ook de complete opbouw. 

Refactor deze methode zodat de naam niet suggereert dat het alleen verzendt.
Maar verdeel ook stukken van deze methode in kleinere methodes zodat de opbouw ergens anders geregeld wordt.

**Comment by joeryhuiden** [comment]
Het is renamed en verdeeld.
