### ISSUE TITLE
Hernoemen van te korte variabelen

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#2]
Geldt zowel voor OverviewController.java als LoginController.java

Hier komt op verschillende plekke te korte variabelen namen voor. Zoals "db" voor "database" en "oc" voor "overviewController"

``` java
    public OverviewController(DatabaseInterface db) {
        this.db = db;
        oc = this;
    }
```

Graag dit hernoemen naar eenduidige, duidelijke termen waardoor ook mogelijk het commentaar verminderd kan worden

**Comment by joeryhuiden** [comment]
renamed
