### ISSUE TITLE
Verhelpen van "Magic numbers" in de code

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#4]
Op een aantal plekken binnen de OverviewController.java komen een aantal "Magic numbers".

Probeer deze in variable te stoppen (zo nodig een constante). Anders met een duidelijke commentaar regel aangeven waarom het getal daar staat.

``` java
clientNode.put("group", 0);
```

**Comment by joeryhuiden** [comment]
commentaar toegevoegd
