### ISSUE TITLE
Opdelen van één methode naar meerdere methodes

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#6]
In de OverviewController.java
in de methode 

``` java
public JSONObject[] createJSONNetworks(Client client) throws JSONException {
```

wordt een hoop duplicate code gebruikt. 
vanaf regel 144 zie je namelijk dezelfde structuur weer terugkomen.

Probeer de code op te delen in meerdere methodes zodat beide stukken in "createJSONNetworks" hier gebruik van kunnen maken

**Comment by joeryhuiden** [comment]
aantal duplicate code extract, maar nog niet alles omdat ik niet zeker weet of het hierdoor "kapot gaat"
