### ISSUE TITLE
Extracten naar nieuwe methode

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/CodeRefactorFW#8]
in de OverviewController.java wordt bij:

``` java
public JSONArray RefreshOverviewClients(User currentUser)
```

gegevens uit de database gehaald en in JSON gestopt.

Dit gebeurd voor een administrator en een "normale" gebruiker. 
Maar bij de administrator gebeurd naast dit

``` java
for (Client c : db.getAllClients()) {
```

niks anders dan bij een normale gebruiker. Dus kan dit worden geextract naar een aparte methode.

**Comment by joeryhuiden** [comment]
gewijzigd
